### ISSUE TITLE
Doesnt use the valid wallet. /solved

### ISSUE THREAD

**Issue by Biosbyt** [RomainLanz/anchor-borrow-bot#18]
I tried everything, but it's not working.

I followed your instruction. Telegram Bot is working, but can't give valid responses since 
the code is using the wrong wallet.
Not sure why and if I look up the wallet in the explorer it's not existent. It even changes the wallet adress even when I didnt change anything.

.env contains my private key from Terra station wallet.

**Comment by RomainLanz** [comment]
Hey @Biosbyt! 👋 

Ensure to not have added any spaces or any character around your key.
It should looks like the following:

```
KEY="xxx xxx xxx xxx"
```

**Comment by Biosbyt** [comment]
Hey @RomainLanz 

Thank you for your quick response. Can't wait to see the bot in action.
I double checked it. No spaces or other characters in between. 
Still not working.

**Comment by RomainLanz** [comment]
Are you sure to modify the `.env` file and not the `.env.example` file?

**Comment by Biosbyt** [comment]
`

# This should be your wallet private key.
KEY="LONGASSKEYHERE"

# Those should be your Telegram Bot information.
BOT_API_KEY="XX"
BOT_CHAT_ID="YY"

# This is the Terra Mainnet - USE IT FOR PRODUCTION
LCD_URL='https://lcd.terra.dev'
CHAIN_ID='columbus-4'

# This is the Terra Testnet - USE IT FOR DEVELOPMENT/TESTING
# LCD_URL='https://tequila-lcd.terra.dev'
# CHAIN_ID='tequila-0004'`

I copied the .env.example file and filled out the variables and renamed it to .env

Since the Telegram bot is working I am clueless why its not reading my wallet key.

Just to be sure: My private key is exported out of the Terra Station Wallet.

**Comment by RomainLanz** [comment]
> I appreciate your support. Is there a possibility to reach out to you via Discord/Telegram?

It is easier for me to do it on GitHub.

> Just to be sure: My private key is exported out of the Terra Station Wallet.

Your private key must be the 24 words seeds given when you create an account.

Can you try to run the bot with the following seed?
```
thumb double knee height erupt umbrella measure recipe monkey mimic language auction seminar post cancel zero sand tip security segment direct claim jump gold
```

Wallet Address should be `terra1zcfxn89amedhu3vw6w72rfrv28czv98tu6whlj`

**Comment by Biosbyt** [comment]
Heureka!

It works. It works like a charme now. Already made the adjustments I wanted. 
I assumed key = private key. 

Thank you!

**Comment by RomainLanz** [comment]
Cool!
Closing then.
