### ISSUE TITLE
Add logging to compound feature

### ISSUE THREAD

**Issue by luigi311** [RomainLanz/anchor-borrow-bot#25]
Using /compound seems to have some inconsistency issues. 

I had 3.16 worth of anc sitting in the UST Borrow that at the time was worth about $7. I initiated the /compound feature and it replied with 
> luigi311_anchor_bot, [22.06.21 16:51]
Selling 0 ANC @ 2.347 UST
New Luna Balance is 0
Compounded... 0.000 ANC for 0.000 bLuna

Looking at my wallet it redeemed but did not sell so it's correct in what it replied with. Looking [here in the source](https://github.com/RomainLanz/anchor-borrow-bot/blob/main/src/Bot.ts#L338) it looks like it does not sell unless its anc value is > 5, I said sure why not. I tested it again in in testnet this time with 1.2 anc being redeemed and it responded with 

> luigi311_anchor_bot, [22.06.21 17:12]
Selling 465 ANC @ 0.000 UST
Swapped 0 UST
New Luna Balance is 0
Compounded... 465.282 ANC for 0.000 bLuna

I am unsure where it got the 465 from but it only redeemed the 1.2 that it had access to and left it in its wallet.

**Comment by luigi311** [comment]
Looks like the anchor UI was just delayed and not showing the correct amount of ANC. It did redeem the 465 ANC from anchor but did not reach the 5 luna threshold it needed to swap to bluna to add to collateral. Perhaps instead of showing that message at all times provide an else condition to all the if statements and specify it did not meet the threshold to swap. Also perhaps add those threshold values to the config.ts to allow the user to customize it.

**Comment by RomainLanz** [comment]
Hey @luigi311! 👋 

Thanks for this issue and your feedback on the `compound` feature.
Indeed, this feature needs some work, more information, and it should be accurate.

I should also add some debugging. It seems to struggle to bond the Luna quite often.
I will have a look! 👍

**Comment by luigi311** [comment]
For logging when compound doesn't do anything it might be best if you just move this line https://github.com/RomainLanz/anchor-borrow-bot/blob/main/src/Bot.ts#L388 into the if (+bLunaBalance > 5)  at the very end and add an else condition outputting

${bLunaBalance.toFixed(3)} bluna is not greater than the threshold of  5. Skipping compound.

Also the final message should just be 

Compounded ${bLunaBalance.toFixed(3)} bluna

and not mention ANC because it's possible for you to have luna in your account which throws a weird compound message of say

Compounded.... 1 ANC for 200 bLuna

if you had 200 Luna just sitting in your wallet which would be amazing if true lol.
