### ISSUE TITLE
Compound: Add delay after swap to allow transaction to finish prior to getting balances

### ISSUE THREAD

**Issue by luigi311** [RomainLanz/anchor-borrow-bot#29]
When compounding depending on the network transaction speed sometimes the transaction will not finish by the time we continue on to the next step to get the balance. We need to add a delay or wait for the transaction to complete or else the compound will not accomplish anything other than claiming the ANC. It then has to be run again causing another claim swap to Luna. Then requires another compound where it claims the ANC for a third time and then swaps the luna to bluna. Thats a total of 3 claims where we have to pay the transaction fees.

 Luigi311, [6/29/21, 10:18 AM]
/compound

luigi311_anchor_bot, [6/29/21, 10:18 AM]
Starting to compound...

luigi311_anchor_bot, [6/29/21, 10:18 AM]
ANC balance: 1
less than 2 minimum... Skipping ANC swap
Luna Balance: 0
less than 1 minimum... Skipping Luna swap
bLuna Balance: 1
less than 1 minimum... Skipping bLuna compound

Luigi311, [6/29/21, 10:19 AM]
/compound

luigi311_anchor_bot, [6/29/21, 10:19 AM]
Starting to compound...

luigi311_anchor_bot, [6/29/21, 10:19 AM]
ANC balance: 12
Swapped ANC for Luna
Luna Balance: 0
less than 1 minimum... Skipping Luna swap
bLuna Balance: 1
less than 1 minimum... Skipping bLuna compound

Luigi311, [6/29/21, 10:22 AM]
/compound

luigi311_anchor_bot, [6/29/21, 10:22 AM]
Starting to compound...

luigi311_anchor_bot, [6/29/21, 10:22 AM]
ANC balance: 1
less than 2 minimum... Skipping ANC swap
Luna Balance: 5
Swapped Luna for bLuna
bLuna Balance: 6
Compounded 5.748 bLuna

**Comment by RomainLanz** [comment]
Fixed!
