### ISSUE TITLE
[Bug] Compound earn doesnt deposit into Anchor Earn

### ISSUE THREAD

**Issue by luigi311** [RomainLanz/anchor-borrow-bot#33]
When running /compound earn it doesn't actually deposit the UST in to earn. It will claim the ANC, sell it and then leave it in the wallet requiring me to manually deposit it to anchor earn even though the bot returns despoited.

**Comment by RomainLanz** [comment]
Hey @luigi311! 👋 

What version are you using, the latest version in `develop` should fix this.

**Comment by luigi311** [comment]
Just updated to the latest develop commit and can confirm it has resolved my issue. Thank!
