### ISSUE TITLE
other mode : low LTV => borrow UST => Luna => bLuna =>provide more bLuna

### ISSUE THREAD

**Issue by ebgd** [RomainLanz/anchor-borrow-bot#36]
In case of low LTV, would it be possible, (instead of auto deposit borrowed UST => aUST) to auto convert borrowed UST=>Luna=>bLuna, and redeposit the bLuna to decrease the LTV
And in case of high LTV, to repay, we withdraw some bLuna, then "instant burn bLuna" => Luna  => UST and repay

May be tricky to code, and also "instant burn" is expensive (gets about -4% luna compared to regular burn, that takes 21 days)
The goal here is to benefit from a Luna uptrend by increasing the Luna/bLuna amount (in case low LTV).

**Comment by RomainLanz** [comment]
Hey @ebgd! 👋 

No, it is not planned to help people doing leverage.
This can be devastating.

**Comment by ebgd** [comment]
right !
